// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PlexClone.Models;
using System;

namespace PlexClone.Migrations
{
    [DbContext(typeof(PlexCloneContext))]
    [Migration("20180522214045_FirstM")]
    partial class FirstM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("PlexClone.Models.File", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Libraryid");

                    b.Property<int>("Moviesid");

                    b.Property<string>("Path");

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.HasIndex("Libraryid");

                    b.HasIndex("Moviesid");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("PlexClone.Models.Libraries", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Folder");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("PlexClone.Models.Movies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Actors");

                    b.Property<string>("IMDBRating");

                    b.Property<string>("Plot");

                    b.Property<string>("Poster");

                    b.Property<string>("Rating");

                    b.Property<string>("RottenTomatoesRating");

                    b.Property<int>("Runtime");

                    b.Property<string>("Title");

                    b.Property<int>("Year");

                    b.Property<DateTime>("created_at");

                    b.Property<string>("genre");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("PlexClone.Models.File", b =>
                {
                    b.HasOne("PlexClone.Models.Libraries", "Library")
                        .WithMany("Files")
                        .HasForeignKey("Libraryid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PlexClone.Models.Movies", "Movie")
                        .WithMany("MovieFiles")
                        .HasForeignKey("Moviesid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
