// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PlexClone.Models;
using System;

namespace PlexClone.Migrations
{
    [DbContext(typeof(PlexCloneContext))]
    [Migration("20180525163816_pathUpdate")]
    partial class pathUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("PlexClone.Models.File", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodecName");

                    b.Property<string>("Duration");

                    b.Property<string>("FilePath");

                    b.Property<string>("Format");

                    b.Property<bool>("HD");

                    b.Property<int?>("Libraryid");

                    b.Property<int?>("Movieid");

                    b.Property<string>("Quality");

                    b.Property<string>("Resolution");

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.HasIndex("Libraryid");

                    b.HasIndex("Movieid");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("PlexClone.Models.Libraries", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Folder");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("PlexClone.Models.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Actors");

                    b.Property<string>("IMDBRating");

                    b.Property<string>("Plot");

                    b.Property<string>("Poster");

                    b.Property<string>("Rating");

                    b.Property<string>("RottenTomatoesRating");

                    b.Property<string>("Runtime");

                    b.Property<string>("Title");

                    b.Property<string>("Year");

                    b.Property<DateTime>("created_at");

                    b.Property<string>("genre");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("PlexClone.Models.File", b =>
                {
                    b.HasOne("PlexClone.Models.Libraries", "Library")
                        .WithMany("Files")
                        .HasForeignKey("Libraryid");

                    b.HasOne("PlexClone.Models.Movie", "Movie")
                        .WithMany("MovieFiles")
                        .HasForeignKey("Movieid");
                });
#pragma warning restore 612, 618
        }
    }
}
